backend:
  name: git-gateway
  branch: main

# アップロードされた画像ファイルのパス
media_folder: "site/static/img"
# アップロードされた画像ファイルの場所
public_folder: "/img"
# ワークフローの追加
publish_mode: editorial_workflow
# 公開サイトのURL
site_url: https://acecore.systems
# サイト編集画面に表示されるリンク
display_url: https://acecore.systems
# 言語設定
locale: "ja"

collections:
  - label: "記事" # 管理画面のサイドバーで使う
    name: "article" # 管理画面のパスで使う　例：/admin/collections/blog
    preview_path: "article/{{slug}}"
    folder: "site/content/article" # Markdownを保存するディレクトリ。Hugoのsectionにあたる
    filter: { field: "type", value: "article" }
    create: true # 新しいページを作ることを許可する
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Markdownのファイル名　例：YYYY-MM-DD-title.md
    fields: # ページ作成画面で使う。Front Matterの値を書く
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "記事の説明", name: "description", widget: "text" }
      - { label: "作成者", name: "author", widget: "text" }
      - { label: "公開日", name: "publishDate", widget: "datetime"}
      - { label: "サムネイル画像", name: "thumbnail", widget: "image" }
      - { label: "サムネイル画像の説明", name: "thumbnailAlt", widget: "string"}
      - { label: "カテゴリー", name: "categories", widget: "list", required: false}
      - { label: "タグ", name: "tags", widget: "list", required: false}
      - { label: "本文", name: "body", widget: "markdown" }
      - { label: "タイプ", name: "type", widget: "hidden", default: "article" }

  - label: "エースサーバー" # 管理画面のサイドバーで使う
    name: "acesv" # 管理画面のパスで使う　例：/admin/collections/blog
    preview_path: "acesv/{{slug}}"
    folder: "site/content/acesv" # Markdownを保存するディレクトリ。Hugoのsectionにあたる
    create: false # 新しいページを作ることを許可する
    fields: # ページ作成画面で使う。Front Matterの値を書く
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "記事の説明", name: "description", widget: "text" }
      - {
          label: "メニュー",
          name: "menu",
          widget: "string",
          default: "メニュー"
        }
      - {
          label: "ページインデックス",
          name: "pageindex",
          widget: "number",
          required: false
        }
      - { label: "本文", name: "body", widget: "markdown" }

  - label: "インデックスページ"
    name: "indexpage"
    files:
      - file: "site/content/_index.md"
        label: "ホームページ"
        name: "home"
        fields:
          - { label: "タイトル", name: "title", widget: "string" }
          - { label: "このページの説明", name: "description", widget: "text" }
          - { label: "本文", name: "body", widget: "markdown" }
      - file: "site/content/acesv/_index.md"
        label: "エースサーバー"
        name: "acesv"
        fields:
          - { label: "タイトル", name: "title", widget: "string" }
          - { label: "このページの説明", name: "description", widget: "text" }
          - { label: "本文", name: "body", widget: "markdown" }
      - file: "site/content/blog/_index.md"
        label: "ブログ"
        name: "blog"
        fields:
          - { label: "タイトル", name: "title", widget: "string" }
          - { label: "このページの説明", name: "description", widget: "text" }
          - { label: "本文", name: "body", widget: "markdown" }
      - file: "site/content/support/_index.md"
        label: "サポート"
        name: "support"
        fields:
          - { label: "タイトル", name: "title", widget: "string" }
          - { label: "このページの説明", name: "description", widget: "text" }
          - { label: "本文", name: "body", widget: "markdown" }
